/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./building.glb --types --keepnames --shadows
*/

import * as THREE from 'three';
import { useCallback } from 'react';
import { useGLTF, Html, useCubeTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { a, useSpring, useSprings } from '@react-spring/three';

type GLTFResult = GLTF & {
    nodes: {
        Base: THREE.Mesh;
        Common: THREE.Mesh;
        Flat001: THREE.Mesh;
        Flat002: THREE.Mesh;
        Flat003: THREE.Mesh;
        Flat004: THREE.Mesh;
        SelectionBox001: THREE.Mesh;
        SelectionBox002: THREE.Mesh;
        SelectionBox003: THREE.Mesh;
        SelectionBox004: THREE.Mesh;
        Common001: THREE.Mesh;
        Flat005: THREE.Mesh;
        Flat006: THREE.Mesh;
        Flat007: THREE.Mesh;
        Flat008: THREE.Mesh;
        Base001: THREE.Mesh;
        SelectionBox005: THREE.Mesh;
        SelectionBox006: THREE.Mesh;
        SelectionBox007: THREE.Mesh;
        SelectionBox008: THREE.Mesh;
        Common002: THREE.Mesh;
        Flat009: THREE.Mesh;
        Flat010: THREE.Mesh;
        Flat011: THREE.Mesh;
        Flat012: THREE.Mesh;
        Base002: THREE.Mesh;
        SelectionBox009: THREE.Mesh;
        SelectionBox010: THREE.Mesh;
        SelectionBox011: THREE.Mesh;
        SelectionBox012: THREE.Mesh;
        Common003: THREE.Mesh;
        Flat013: THREE.Mesh;
        Flat014: THREE.Mesh;
        Flat015: THREE.Mesh;
        Flat016: THREE.Mesh;
        Base003: THREE.Mesh;
        SelectionBox013: THREE.Mesh;
        SelectionBox014: THREE.Mesh;
        SelectionBox015: THREE.Mesh;
        SelectionBox016: THREE.Mesh;
        Common004: THREE.Mesh;
        Flat017: THREE.Mesh;
        Flat018: THREE.Mesh;
        Flat019: THREE.Mesh;
        Flat020: THREE.Mesh;
        Base004: THREE.Mesh;
        SelectionBox017: THREE.Mesh;
        SelectionBox018: THREE.Mesh;
        SelectionBox019: THREE.Mesh;
        SelectionBox020: THREE.Mesh;
        Common005: THREE.Mesh;
        Flat021: THREE.Mesh;
        Flat022: THREE.Mesh;
        Flat023: THREE.Mesh;
        Flat024: THREE.Mesh;
        Base005: THREE.Mesh;
        SelectionBox021: THREE.Mesh;
        SelectionBox022: THREE.Mesh;
        SelectionBox023: THREE.Mesh;
        SelectionBox024: THREE.Mesh;
        Common006: THREE.Mesh;
        Flat025: THREE.Mesh;
        Flat026: THREE.Mesh;
        Flat027: THREE.Mesh;
        Flat028: THREE.Mesh;
        Base006: THREE.Mesh;
        SelectionBox025: THREE.Mesh;
        SelectionBox026: THREE.Mesh;
        SelectionBox027: THREE.Mesh;
        SelectionBox028: THREE.Mesh;
        Basement: THREE.Mesh;
        Roof: THREE.Mesh;
    };
    materials: {
        ConcreteMaterial: THREE.MeshStandardMaterial;
        CommonAreaMaterial: THREE.MeshStandardMaterial;
        ApartmentMaterial: THREE.MeshStandardMaterial;
        SelectionHover: THREE.MeshStandardMaterial;
        SelectionSelect: THREE.MeshStandardMaterial;
        SelectionDefault: THREE.MeshStandardMaterial;
    };
};

export type BuildingProps = JSX.IntrinsicElements['group'] & {
    selectedApartment: string | null;
    selectedFloorNumber: number | null;
    hoveredApartment: string | null;
    showFloorLabels: boolean;
    showSelectionBoxes: boolean;
    availableSelectionBoxes: string[] | null;
};

export function Model(props: BuildingProps) {
    const { nodes, materials } = useGLTF('/building.glb') as GLTFResult;
    const envMap = useCubeTexture(
        ['px.png', 'nx.png', 'py.png', 'ny.png', 'pz.png', 'nz.png'],
        { path: '/environment/' }
    );

    const [{ y: roofY }] = useSpring(
        {
            y:
                props.selectedFloorNumber === null ||
                props.selectedFloorNumber === undefined
                    ? 33.4
                    : 100,
            config: {
                mass: 1,
                tension: 90,
                friction: 26,
                precision: 0.01,
            },
        },
        [props.selectedFloorNumber]
    );

    const [springs] = useSprings(
        7,
        (i) => {
            return {
                y:
                    props.selectedFloorNumber &&
                    props.selectedFloorNumber < i + 1
                        ? 100
                        : i * 4.2 + 4, // first floor's `y` is 4, every following is higher by 4.2
                config: {
                    mass: 1,
                    tension: 170 - i * 10,
                    friction: 26,
                    precision: 0.01,
                },
            };
        },
        [props.selectedFloorNumber]
    );

    const getMaterial = useCallback(
        (id: string) => {
            id = 'Flat' + id;
            if (props.selectedApartment === id) {
                return materials.SelectionSelect;
            }
            if (props.hoveredApartment === id) {
                return materials.SelectionHover;
            }
            return materials.SelectionDefault;
        },
        [
            materials.SelectionDefault,
            materials.SelectionHover,
            materials.SelectionSelect,
            props.hoveredApartment,
            props.selectedApartment,
        ]
    );

    return (
        <group {...props} dispose={null}>
            <a.group
                name="Floor001"
                // position={[0, 4, 0]}
                position-y={springs[0].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">01</div>
                    </Html>
                )}
                <mesh
                    name="Base"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="Common"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat001.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 1 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">001</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat002.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 1 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">002</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat003.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 1 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">003</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat004.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 1 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">004</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="SelectionBox001"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox001.geometry}
                    material={getMaterial('001')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox002"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox002.geometry}
                    material={getMaterial('002')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox003"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox003.geometry}
                    material={getMaterial('003')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox004"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox004.geometry}
                    material={getMaterial('004')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <a.group
                name="Floor002"
                // position={[0, 8.2, 0]}
                position-y={springs[1].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">02</div>
                    </Html>
                )}
                <mesh
                    name="Common001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common001.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat005.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 2 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">005</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat006.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 2 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">006</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat007"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat007.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 2 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">007</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat008"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat008.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 2 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">008</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Base001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base001.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="SelectionBox005"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox005.geometry}
                    material={getMaterial('005')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox006"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox006.geometry}
                    material={getMaterial('006')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox007"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox007.geometry}
                    material={getMaterial('007')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox008"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox008.geometry}
                    material={getMaterial('008')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <a.group
                name="Floor003"
                // position={[0, 12.4, 0]}
                position-y={springs[2].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">03</div>
                    </Html>
                )}
                <mesh
                    name="Common002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common002.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat009"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat009.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 3 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">009</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat010"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat010.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 3 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">010</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat011"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat011.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 3 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">011</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat012"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat012.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 3 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">012</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Base002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base002.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="SelectionBox009"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox009.geometry}
                    material={getMaterial('009')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox010"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox010.geometry}
                    material={getMaterial('010')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox011"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox011.geometry}
                    material={getMaterial('011')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox012"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox012.geometry}
                    material={getMaterial('012')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <a.group
                name="Floor004"
                // position={[0, 16.6, 0]}
                position-y={springs[3].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">04</div>
                    </Html>
                )}
                <mesh
                    name="Common003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common003.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat013"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat013.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 4 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">013</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat014"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat014.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 4 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">014</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat015"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat015.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 4 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">015</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat016"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat016.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 4 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">016</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Base003"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base003.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="SelectionBox013"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox013.geometry}
                    material={getMaterial('013')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox014"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox014.geometry}
                    material={getMaterial('014')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox015"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox015.geometry}
                    material={getMaterial('015')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox016"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox016.geometry}
                    material={getMaterial('016')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <a.group
                name="Floor005"
                // position={[0, 20.8, 0]}
                position-y={springs[4].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">05</div>
                    </Html>
                )}
                <mesh
                    name="Common004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common004.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat017"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat017.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 5 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">017</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat018"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat018.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 5 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">018</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat019"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat019.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 5 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">019</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat020"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat020.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 5 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">020</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Base004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base004.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="SelectionBox017"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox017.geometry}
                    material={getMaterial('017')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox018"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox018.geometry}
                    material={getMaterial('018')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox019"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox019.geometry}
                    material={getMaterial('019')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox020"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox020.geometry}
                    material={getMaterial('020')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <a.group
                name="Floor006"
                // position={[0, 25, 0]}
                position-y={springs[5].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">06</div>
                    </Html>
                )}
                <mesh
                    name="Common005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common005.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat021"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat021.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 6 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">021</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat022"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat022.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 6 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">022</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat023"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat023.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 6 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">023</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat024"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat024.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 6 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">024</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Base005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base005.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="SelectionBox021"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox021.geometry}
                    material={getMaterial('021')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox022"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox022.geometry}
                    material={getMaterial('022')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox023"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox023.geometry}
                    material={getMaterial('023')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox024"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox024.geometry}
                    material={getMaterial('024')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <a.group
                name="Floor007"
                // position={[0, 29.2, 0]}
                position-y={springs[6].y}
            >
                {props.showFloorLabels && (
                    <Html transform sprite distanceFactor={15}>
                        <div className="floor-label">07</div>
                    </Html>
                )}
                <mesh
                    name="Common006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Common006.geometry}
                    material={materials.CommonAreaMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[0, 0.2, 0]}
                />
                <mesh
                    name="Flat025"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat025.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 7 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">025</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat026"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat026.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 7 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">026</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat027"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat027.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, -4.5]}
                >
                    {props.selectedFloorNumber === 7 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">027</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Flat028"
                    castShadow
                    receiveShadow
                    geometry={nodes.Flat028.geometry}
                    material={materials.ApartmentMaterial}
                    material-metalness={0.7}
                    material-envMap={envMap}
                    position={[-5.5, 0.2, 4.5]}
                >
                    {props.selectedFloorNumber === 7 && (
                        <Html transform sprite distanceFactor={15}>
                            <div className="apartment-label">028</div>
                        </Html>
                    )}
                </mesh>
                <mesh
                    name="Base006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Base006.geometry}
                    material={materials.ConcreteMaterial}
                    material-envMap={envMap}
                />
                <mesh
                    name="SelectionBox025"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox025.geometry}
                    material={getMaterial('025')}
                    position={[6, 0.22, 5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox026"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox026.geometry}
                    material={getMaterial('026')}
                    position={[6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox027"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox027.geometry}
                    material={getMaterial('027')}
                    position={[-6, 0.22, -5]}
                    scale={1.01}
                />
                <mesh
                    name="SelectionBox028"
                    visible={props.showSelectionBoxes}
                    castShadow
                    receiveShadow
                    geometry={nodes.SelectionBox028.geometry}
                    material={getMaterial('028')}
                    position={[-6, 0.22, 5]}
                    scale={1.01}
                />
            </a.group>
            <mesh
                name="Basement"
                castShadow
                receiveShadow
                geometry={nodes.Basement.geometry}
                material={materials.ConcreteMaterial}
                material-envMap={envMap}
            />
            <a.mesh
                name="Roof"
                castShadow
                receiveShadow
                geometry={nodes.Roof.geometry}
                material={materials.ConcreteMaterial}
                material-envMap={envMap}
                position={[0, 33.4, 0]}
                position-y={roofY}
            />
        </group>
    );
}

useGLTF.preload('/building.glb');
