/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 City_001.glb --types --keepnames --shadows
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        City_001_Base_Cube: THREE.Mesh;
        Cylinder020: THREE.Mesh;
        Cylinder020_1: THREE.Mesh;
        City_001_Bush_01: THREE.Mesh;
        Cylinder003: THREE.Mesh;
        Cylinder003_1: THREE.Mesh;
        Cube030: THREE.Mesh;
        Cube030_1: THREE.Mesh;
        Cube030_2: THREE.Mesh;
        Cube030_3: THREE.Mesh;
        City_001_Building_011: THREE.Mesh;
        Cube027: THREE.Mesh;
        Cube027_1: THREE.Mesh;
        Cube027_2: THREE.Mesh;
        City_001_Building_021: THREE.Mesh;
        City_001_Building_020: THREE.Mesh;
        City_001_Building_019: THREE.Mesh;
        City_001_Building_018: THREE.Mesh;
        City_001_Building_016: THREE.Mesh;
        Cube018: THREE.Mesh;
        Cube018_1: THREE.Mesh;
        Cube018_2: THREE.Mesh;
        Cube018_3: THREE.Mesh;
        Cube016: THREE.Mesh;
        Cube016_1: THREE.Mesh;
        Cube015: THREE.Mesh;
        Cube015_1: THREE.Mesh;
        Cube015_2: THREE.Mesh;
        Cube015_3: THREE.Mesh;
        City_001_Building_010: THREE.Mesh;
        City_001_Building_009: THREE.Mesh;
        City_001_Building_008: THREE.Mesh;
        City_001_Building_007: THREE.Mesh;
        City_001_Building_006: THREE.Mesh;
        City_001_Building_005: THREE.Mesh;
        City_001_Building_004: THREE.Mesh;
        City_001_Building_003: THREE.Mesh;
        City_001_Building_002: THREE.Mesh;
        City_001_Building_001: THREE.Mesh;
        City_001_Building_base_01: THREE.Mesh;
        Cylinder002: THREE.Mesh;
        Cylinder002_1: THREE.Mesh;
        Cube002: THREE.Mesh;
        Cube002_1: THREE.Mesh;
    };
    materials: {
        City_Material: THREE.MeshStandardMaterial;
        Brown_01: THREE.MeshStandardMaterial;
        Green_03: THREE.MeshStandardMaterial;
        Green_01: THREE.MeshStandardMaterial;
        White: THREE.MeshStandardMaterial;
        Windows_03: THREE.MeshStandardMaterial;
        Windows_04: THREE.MeshStandardMaterial;
        Windows_02: THREE.MeshStandardMaterial;
        Gray_02: THREE.MeshStandardMaterial;
        Red_01: THREE.MeshStandardMaterial;
        Gray_04: THREE.MeshStandardMaterial;
        Fountain_01: THREE.MeshStandardMaterial;
        Fountain_Water: THREE.MeshStandardMaterial;
        Green_02: THREE.MeshStandardMaterial;
    };
};

const getTreeHelper = () => {
    return Array.from({ length: 20 }).map(() => {
        const baseAngle = (Math.PI / 3) * Math.random() + Math.PI / 12;
        const angle = (Math.PI / 2) * Math.round(Math.random() * 4) + baseAngle;
        const radius = 11 * Math.random() + 10;

        const x = Math.sin(angle) * radius;
        const y = 0.7;
        const z = Math.cos(angle) * radius;
        return new THREE.Vector3(x, y, z);
    });
};

const treeHelper1 = getTreeHelper();
const treeHelper2 = getTreeHelper();

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/City_001.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                name="City_001_Base_Cube"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Base_Cube.geometry}
                material={materials.City_Material}
                position={[0.84, -9.93, -2.31]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            {treeHelper1.map((position, i) => (
                <group
                    key={i}
                    name="City_001_Tree_002"
                    position={position}
                    rotation={[0, -1.44, 0]}
                >
                    <mesh
                        name="Cylinder020"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder020.geometry}
                        material={materials.Brown_01}
                    />
                    <mesh
                        name="Cylinder020_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder020_1.geometry}
                        material={materials.Green_03}
                    />
                </group>
            ))}
            {treeHelper2.map((position, i) => (
                <group key={i} name="City_001_Tree_01" position={position}>
                    <mesh
                        name="Cylinder003"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003.geometry}
                        material={materials.Brown_01}
                    />
                    <mesh
                        name="Cylinder003_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003_1.geometry}
                        material={materials.Green_03}
                    />
                </group>
            ))}
            <mesh
                name="City_001_Bush_01"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Bush_01.geometry}
                material={materials.Green_01}
                position={[55.09, 0.53, 52.11]}
                rotation={[0, 1.57, 0]}
            />
            <group name="City_001_Building_012" position={[8.84, 21, 49.94]}>
                <mesh
                    name="Cube030"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube030_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030_1.geometry}
                    material={materials.Windows_03}
                />
                <mesh
                    name="Cube030_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030_2.geometry}
                    material={materials.Windows_04}
                />
                <mesh
                    name="Cube030_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030_3.geometry}
                    material={materials.Windows_02}
                />
            </group>
            <mesh
                name="City_001_Building_011"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_011.geometry}
                material={materials.City_Material}
                position={[0.76, 9.49, -58.08]}
            />
            <group name="City_001_Building_017" position={[-41.19, 6.16, 14.6]}>
                <mesh
                    name="Cube027"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube027_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027_1.geometry}
                    material={materials.Windows_02}
                />
                <mesh
                    name="Cube027_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027_2.geometry}
                    material={materials.Gray_02}
                />
            </group>
            <mesh
                name="City_001_Building_021"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_021.geometry}
                material={materials.City_Material}
                position={[-41.23, 6.16, -41.87]}
                rotation={[0, 1.57, 0]}
            />
            <mesh
                name="City_001_Building_020"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_020.geometry}
                material={materials.City_Material}
                position={[42.89, 6.16, -41.77]}
            />
            <mesh
                name="City_001_Building_019"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_019.geometry}
                material={materials.City_Material}
                position={[42.89, 6.16, -57.73]}
            />
            <mesh
                name="City_001_Building_018"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_018.geometry}
                material={materials.City_Material}
                position={[-41.36, 6.16, -57.73]}
            />
            <mesh
                name="City_001_Building_016"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_016.geometry}
                material={materials.City_Material}
                position={[-41.13, 6.16, -17.33]}
            />
            <group name="City_001_Building_015" position={[-41.13, 6.16, -1.7]}>
                <mesh
                    name="Cube018"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018.geometry}
                    material={materials.Red_01}
                />
                <mesh
                    name="Cube018_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018_1.geometry}
                    material={materials.Windows_02}
                />
                <mesh
                    name="Cube018_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018_2.geometry}
                    material={materials.Gray_02}
                />
                <mesh
                    name="Cube018_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018_3.geometry}
                    material={materials.White}
                />
            </group>
            <group
                name="City_001_Building_014"
                position={[-41.36, 6.16, 58.24]}
            >
                <mesh
                    name="Cube016"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube016.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube016_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube016_1.geometry}
                    material={materials.Gray_02}
                />
            </group>
            <group
                name="City_001_Building_013"
                position={[-41.36, 6.16, 42.27]}
            >
                <mesh
                    name="Cube015"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube015_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015_1.geometry}
                    material={materials.Windows_02}
                />
                <mesh
                    name="Cube015_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015_2.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube015_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015_3.geometry}
                    material={materials.Gray_04}
                />
            </group>
            <mesh
                name="City_001_Building_010"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_010.geometry}
                material={materials.City_Material}
                position={[0.78, 6.16, -41.47]}
            />
            <mesh
                name="City_001_Building_009"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_009.geometry}
                material={materials.City_Material}
                position={[17.85, 6.16, -43.34]}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
                name="City_001_Building_008"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_008.geometry}
                material={materials.City_Material}
                position={[17.85, 6.16, -59.3]}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
                name="City_001_Building_007"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_007.geometry}
                material={materials.City_Material}
                position={[-16.47, 6.16, -59.3]}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
                name="City_001_Building_006"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_006.geometry}
                material={materials.City_Material}
                position={[-16.47, 6.16, -43.34]}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
                name="City_001_Building_005"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_005.geometry}
                material={materials.City_Material}
                position={[42.89, 6.16, 42.27]}
            />
            <mesh
                name="City_001_Building_004"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_004.geometry}
                material={materials.City_Material}
                position={[42.89, 6.16, 58.24]}
            />
            <mesh
                name="City_001_Building_003"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_003.geometry}
                material={materials.City_Material}
                position={[42.73, 6.16, 14.26]}
            />
            <mesh
                name="City_001_Building_002"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_002.geometry}
                material={materials.City_Material}
                position={[42.73, 6.16, -1.7]}
            />
            <mesh
                name="City_001_Building_001"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_001.geometry}
                material={materials.City_Material}
                position={[42.73, 6.16, -17.33]}
            />
            <mesh
                name="City_001_Building_base_01"
                castShadow
                receiveShadow
                geometry={nodes.City_001_Building_base_01.geometry}
                material={materials.White}
                position={[0.37, 0.44, -47.5]}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
            <group
                visible={false}
                name="City_001_Fountain"
                position={[0.81, 0.93, -0.44]}
            >
                <mesh
                    name="Cylinder002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder002.geometry}
                    material={materials.Fountain_01}
                />
                <mesh
                    name="Cylinder002_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder002_1.geometry}
                    material={materials.Fountain_Water}
                />
            </group>
            <group name="City_001_Park_path" position={[0.81, -0.48, -0.44]}>
                <mesh
                    name="Cube002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002.geometry}
                    material={materials.Green_02}
                />
                <mesh
                    name="Cube002_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_1.geometry}
                    material={materials.White}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/City_001.glb');
