/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/asia_building/v1.gltf --types
*/

import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        group26_2_rooftop_0123_0: THREE.Mesh;
        pCube116_2_rooftop_0124_0: THREE.Mesh;
        pCube117_2_rooftop_0121_0: THREE.Mesh;
        pCube118_2_rooftop_0119_0: THREE.Mesh;
        pCube119_2_rooftop_0125_0: THREE.Mesh;
        pCube120_2_rooftop_0131_0: THREE.Mesh;
        pCube121_2_rooftop_0126_0: THREE.Mesh;
        pCube122_2_rooftop_0128_0: THREE.Mesh;
        pCube123_2_rooftop_0129_0: THREE.Mesh;
        pCube124_2_rooftop_0130_0: THREE.Mesh;
        pPlane197_2_rooftop_0122_0: THREE.Mesh;
        pPlane198_2_rooftop_0120_0: THREE.Mesh;
        pPlane199_2_rooftop_0117_0: THREE.Mesh;
        pPlane200_2_rooftop_0118_0: THREE.Mesh;
        pPlane201_2_rooftop_0127_0: THREE.Mesh;
        group26_rooftop_018_0: THREE.Mesh;
        pCube116_rooftop_019_0: THREE.Mesh;
        pCube117_rooftop_016_0: THREE.Mesh;
        pCube118_rooftop_014_0: THREE.Mesh;
        pCube119_rooftop_0110_0: THREE.Mesh;
        pCube120_rooftop_0116_0: THREE.Mesh;
        pCube121_rooftop_0111_0: THREE.Mesh;
        pCube122_rooftop_0113_0: THREE.Mesh;
        pCube123_rooftop_0114_0: THREE.Mesh;
        pCube124_rooftop_0115_0: THREE.Mesh;
        pPlane197_rooftop_017_0: THREE.Mesh;
        pPlane198_rooftop_015_0: THREE.Mesh;
        pPlane199_rooftop_012_0: THREE.Mesh;
        pPlane200_rooftop_013_0: THREE.Mesh;
        pPlane201_rooftop_0112_0: THREE.Mesh;
        group26_3_rooftop_0138_0: THREE.Mesh;
        pCube116_3_rooftop_0139_0: THREE.Mesh;
        pCube117_3_rooftop_0136_0: THREE.Mesh;
        pCube118_3_rooftop_0134_0: THREE.Mesh;
        pCube119_3_rooftop_0140_0: THREE.Mesh;
        pCube121_3_rooftop_0141_0: THREE.Mesh;
        pCube122_3_rooftop_0142_0: THREE.Mesh;
        pCube123_3_rooftop_0143_0: THREE.Mesh;
        pCube124_3_rooftop_0144_0: THREE.Mesh;
        pPlane197_3_rooftop_0137_0: THREE.Mesh;
        pPlane198_3_rooftop_0135_0: THREE.Mesh;
        pPlane199_3_rooftop_0132_0: THREE.Mesh;
        pPlane200_3_rooftop_0133_0: THREE.Mesh;
        polySurface3488_concrete_021_0: THREE.Mesh;
        polySurface3488_concrete_fine1_0: THREE.Mesh;
        polySurface3489_concrete_022_0: THREE.Mesh;
        polySurface3489_rooftop_01_0: THREE.Mesh;
        polySurface3490_concrete_023_0: THREE.Mesh;
        polySurface3490_rooftop_011_0: THREE.Mesh;
        apartment_02_fine_build_01_0: THREE.Mesh;
        apartment_02_fine_concrete_0: THREE.Mesh;
        apartment_02_fine_concrete_02_0: THREE.Mesh;
        apartment_02_fine_concrete_fine_0: THREE.Mesh;
        Plane: THREE.Mesh;
    };
    materials: {
        ['rooftop_01.068']: THREE.MeshStandardMaterial;
        ['rooftop_01.069']: THREE.MeshStandardMaterial;
        ['rooftop_01.066']: THREE.MeshStandardMaterial;
        ['rooftop_01.064']: THREE.MeshStandardMaterial;
        ['rooftop_01.070']: THREE.MeshStandardMaterial;
        ['rooftop_01.076']: THREE.MeshStandardMaterial;
        ['rooftop_01.071']: THREE.MeshStandardMaterial;
        ['rooftop_01.073']: THREE.MeshStandardMaterial;
        ['rooftop_01.074']: THREE.MeshStandardMaterial;
        ['rooftop_01.075']: THREE.MeshStandardMaterial;
        ['rooftop_01.067']: THREE.MeshStandardMaterial;
        ['rooftop_01.065']: THREE.MeshStandardMaterial;
        ['rooftop_01.062']: THREE.MeshStandardMaterial;
        ['rooftop_01.063']: THREE.MeshStandardMaterial;
        ['rooftop_01.072']: THREE.MeshStandardMaterial;
        ['rooftop_01.053']: THREE.MeshStandardMaterial;
        ['rooftop_01.054']: THREE.MeshStandardMaterial;
        ['rooftop_01.051']: THREE.MeshStandardMaterial;
        ['rooftop_01.049']: THREE.MeshStandardMaterial;
        ['rooftop_01.055']: THREE.MeshStandardMaterial;
        ['rooftop_01.061']: THREE.MeshStandardMaterial;
        ['rooftop_01.056']: THREE.MeshStandardMaterial;
        ['rooftop_01.058']: THREE.MeshStandardMaterial;
        ['rooftop_01.059']: THREE.MeshStandardMaterial;
        ['rooftop_01.060']: THREE.MeshStandardMaterial;
        ['rooftop_01.052']: THREE.MeshStandardMaterial;
        ['rooftop_01.050']: THREE.MeshStandardMaterial;
        ['rooftop_01.047']: THREE.MeshStandardMaterial;
        ['rooftop_01.048']: THREE.MeshStandardMaterial;
        ['rooftop_01.057']: THREE.MeshStandardMaterial;
        ['rooftop_01.083']: THREE.MeshStandardMaterial;
        ['rooftop_01.084']: THREE.MeshStandardMaterial;
        ['rooftop_01.081']: THREE.MeshStandardMaterial;
        ['rooftop_01.079']: THREE.MeshStandardMaterial;
        ['rooftop_01.085']: THREE.MeshStandardMaterial;
        ['rooftop_01.086']: THREE.MeshStandardMaterial;
        ['rooftop_01.087']: THREE.MeshStandardMaterial;
        ['rooftop_01.088']: THREE.MeshStandardMaterial;
        ['rooftop_01.089']: THREE.MeshStandardMaterial;
        ['rooftop_01.082']: THREE.MeshStandardMaterial;
        ['rooftop_01.080']: THREE.MeshStandardMaterial;
        ['rooftop_01.077']: THREE.MeshStandardMaterial;
        ['rooftop_01.078']: THREE.MeshStandardMaterial;
        ['concrete_02.005']: THREE.MeshStandardMaterial;
        ['concrete_fine.003']: THREE.MeshStandardMaterial;
        ['concrete_02.006']: THREE.MeshStandardMaterial;
        ['rooftop_01.045']: THREE.MeshStandardMaterial;
        ['concrete_02.007']: THREE.MeshStandardMaterial;
        ['rooftop_01.046']: THREE.MeshStandardMaterial;
        ['build_01.001']: THREE.MeshStandardMaterial;
        ['concrete.001']: THREE.MeshStandardMaterial;
        ['concrete_02.004']: THREE.MeshStandardMaterial;
        ['concrete_fine.002']: THREE.MeshStandardMaterial;
        ['Selection.001']: THREE.MeshStandardMaterial;
    };
};

const semiTransparentMaterial = new THREE.MeshPhongMaterial({
    color: 0x00ff00,
    opacity: 0.5,
    transparent: true,
});

const transparentMaterial = new THREE.MeshPhongMaterial({
    color: 0x00ff00,
    opacity: 0,
    transparent: true,
});

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(
        './asia_building/v1.gltf'
    ) as GLTFResult;

    const [hovered, hover] = useState(false);

    return (
        <group {...props} dispose={null}>
            <mesh
                onPointerMove={() => hover(true)}
                onPointerOut={() => hover(false)}
                geometry={nodes.Plane.geometry}
                material={
                    hovered ? semiTransparentMaterial : transparentMaterial
                }
                position={[-1.01, 32.31, 0]}
            />
            <group position={[0, 0, 60]}>
                <mesh
                    geometry={nodes.group26_2_rooftop_0123_0.geometry}
                    material={materials['rooftop_01.068']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube116_2_rooftop_0124_0.geometry}
                    material={materials['rooftop_01.069']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube117_2_rooftop_0121_0.geometry}
                    material={materials['rooftop_01.066']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube118_2_rooftop_0119_0.geometry}
                    material={materials['rooftop_01.064']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube119_2_rooftop_0125_0.geometry}
                    material={materials['rooftop_01.070']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube120_2_rooftop_0131_0.geometry}
                    material={materials['rooftop_01.076']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube121_2_rooftop_0126_0.geometry}
                    material={materials['rooftop_01.071']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube122_2_rooftop_0128_0.geometry}
                    material={materials['rooftop_01.073']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube123_2_rooftop_0129_0.geometry}
                    material={materials['rooftop_01.074']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube124_2_rooftop_0130_0.geometry}
                    material={materials['rooftop_01.075']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane197_2_rooftop_0122_0.geometry}
                    material={materials['rooftop_01.067']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane198_2_rooftop_0120_0.geometry}
                    material={materials['rooftop_01.065']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane199_2_rooftop_0117_0.geometry}
                    material={materials['rooftop_01.062']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane200_2_rooftop_0118_0.geometry}
                    material={materials['rooftop_01.063']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane201_2_rooftop_0127_0.geometry}
                    material={materials['rooftop_01.072']}
                    position={[-30, 0, 159.99]}
                />
            </group>
            <group
                position={[-1.84, 0, -59.22]}
                rotation={[Math.PI, 0, Math.PI]}
            >
                <mesh
                    geometry={nodes.group26_rooftop_018_0.geometry}
                    material={materials['rooftop_01.053']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube116_rooftop_019_0.geometry}
                    material={materials['rooftop_01.054']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube117_rooftop_016_0.geometry}
                    material={materials['rooftop_01.051']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube118_rooftop_014_0.geometry}
                    material={materials['rooftop_01.049']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube119_rooftop_0110_0.geometry}
                    material={materials['rooftop_01.055']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube120_rooftop_0116_0.geometry}
                    material={materials['rooftop_01.061']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube121_rooftop_0111_0.geometry}
                    material={materials['rooftop_01.056']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube122_rooftop_0113_0.geometry}
                    material={materials['rooftop_01.058']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube123_rooftop_0114_0.geometry}
                    material={materials['rooftop_01.059']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pCube124_rooftop_0115_0.geometry}
                    material={materials['rooftop_01.060']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane197_rooftop_017_0.geometry}
                    material={materials['rooftop_01.052']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane198_rooftop_015_0.geometry}
                    material={materials['rooftop_01.050']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane199_rooftop_012_0.geometry}
                    material={materials['rooftop_01.047']}
                    position={[-30, 3.08, 160.69]}
                />
                <mesh
                    geometry={nodes.pPlane200_rooftop_013_0.geometry}
                    material={materials['rooftop_01.048']}
                    position={[-30, 0, 159.99]}
                />
                <mesh
                    geometry={nodes.pPlane201_rooftop_0112_0.geometry}
                    material={materials['rooftop_01.057']}
                    position={[-30, 0, 159.99]}
                />
            </group>
            <group position={[-30, 0, 219.99]}>
                <mesh
                    geometry={nodes.group26_3_rooftop_0138_0.geometry}
                    material={materials['rooftop_01.083']}
                />
                <mesh
                    geometry={nodes.pCube116_3_rooftop_0139_0.geometry}
                    material={materials['rooftop_01.084']}
                />
                <mesh
                    geometry={nodes.pCube117_3_rooftop_0136_0.geometry}
                    material={materials['rooftop_01.081']}
                />
                <mesh
                    geometry={nodes.pCube118_3_rooftop_0134_0.geometry}
                    material={materials['rooftop_01.079']}
                />
                <mesh
                    geometry={nodes.pCube119_3_rooftop_0140_0.geometry}
                    material={materials['rooftop_01.085']}
                />
                <mesh
                    geometry={nodes.pCube121_3_rooftop_0141_0.geometry}
                    material={materials['rooftop_01.086']}
                />
                <mesh
                    geometry={nodes.pCube122_3_rooftop_0142_0.geometry}
                    material={materials['rooftop_01.087']}
                />
                <mesh
                    geometry={nodes.pCube123_3_rooftop_0143_0.geometry}
                    material={materials['rooftop_01.088']}
                />
                <mesh
                    geometry={nodes.pCube124_3_rooftop_0144_0.geometry}
                    material={materials['rooftop_01.089']}
                />
                <mesh
                    geometry={nodes.pPlane197_3_rooftop_0137_0.geometry}
                    material={materials['rooftop_01.082']}
                />
                <mesh
                    geometry={nodes.pPlane198_3_rooftop_0135_0.geometry}
                    material={materials['rooftop_01.080']}
                />
                <mesh
                    geometry={nodes.pPlane199_3_rooftop_0132_0.geometry}
                    material={materials['rooftop_01.077']}
                />
                <mesh
                    geometry={nodes.pPlane200_3_rooftop_0133_0.geometry}
                    material={materials['rooftop_01.078']}
                />
            </group>
            <group position={[-30, 0, 219.99]}>
                <mesh
                    geometry={nodes.polySurface3488_concrete_021_0.geometry}
                    material={materials['concrete_02.005']}
                />
                <mesh
                    geometry={nodes.polySurface3488_concrete_fine1_0.geometry}
                    material={materials['concrete_fine.003']}
                />
            </group>
            <group position={[-30, 0, 219.99]}>
                <mesh
                    geometry={nodes.polySurface3489_concrete_022_0.geometry}
                    material={materials['concrete_02.006']}
                />
                <mesh
                    geometry={nodes.polySurface3489_rooftop_01_0.geometry}
                    material={materials['rooftop_01.045']}
                />
            </group>
            <group position={[-30, 0, 219.99]}>
                <mesh
                    geometry={nodes.polySurface3490_concrete_023_0.geometry}
                    material={materials['concrete_02.007']}
                />
                <mesh
                    geometry={nodes.polySurface3490_rooftop_011_0.geometry}
                    material={materials['rooftop_01.046']}
                />
            </group>
            <mesh
                geometry={nodes.apartment_02_fine_build_01_0.geometry}
                material={materials['build_01.001']}
            />
            <mesh
                geometry={nodes.apartment_02_fine_concrete_0.geometry}
                material={materials['concrete.001']}
            />
            <mesh
                geometry={nodes.apartment_02_fine_concrete_02_0.geometry}
                material={materials['concrete_02.004']}
            />
            <mesh
                geometry={nodes.apartment_02_fine_concrete_fine_0.geometry}
                material={materials['concrete_fine.002']}
            />
        </group>
    );
}

useGLTF.preload('./asia_building/v1.gltf');
